apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: tripinsights-dev
  labels:
    run: tripviewer
spec:
  type: ClusterIP
  selector:
    app: tripviewer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP