apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-sync
  namespace: api-dev
spec:
  provider: azure
  secretObjects:                     # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: sqluser              # name of the Kubernetes Secret object
    type: Opaque
    data: 
    - objectName: "sqluser"          # name of the mounted content to sync, such as the object name or object alias 
      key: sqluser                   # data field to populate. This must match in deployment yaml for key
  - secretName: sqlpassword          # name of the Kubernetes Secret object
    type: Opaque
    data: 
    - objectName: "sqlpassword"      # name of the mounted content to sync, such as the object name or object alias 
      key: sqlpassword               # data field to populate. This must match in deployment yaml for key
  - secretName: sqlserver            # name of the Kubernetes Secret object
    type: Opaque
    data: 
    - objectName: "sqlserver"        # name of the mounted content to sync, such as the object name or object alias 
      key: sqlserver                 # data field to populate. This must match in deployment yaml for key
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "d911adc1-18fb-47f0-bb82-b46b4bf1068a"
    keyvaultName: "challenge04keyvault"
    cloudName: AzurePublicCloud
    objects: |
       array:
         - |
          objectName: sqluser      # key vault secret name
          objectType: secret       # object types: secret, key or cert
         - |
          objectName: sqlpassword  # key vault secret name
          objectType: secret       # object types: secret, key or cert
         - |
          objectName: sqlserver    # key vault secret name
          objectType: secret       # object types: secret, key or cert
    resourceGroup: "challenge04"
    subscriptionId: "4631b064-cd36-4785-99b7-195ab94da98b"
    tenantId: "e75b282e-8606-4fa1-b5a5-7a98be2cad2a"