apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: tripinsights-dev
  labels:
    run: trips
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP