apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api-dev
  labels:
    run: trips
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP