apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api-dev
  labels:
    run: poi
spec:
  type: ClusterIP
  selector:
    app: poi
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP