apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: tripinsights-dev
  labels:
    run: userprofile
spec:
  type: ClusterIP
  selector:
    app: userprofile
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP